# This workflow will do a clean installation of node dependencies, cache/restore them, 
# build the source code, and run tests across different versions of Node.js.

name: frontend_CICD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Enables manual trigger

# 🔹 FIX: Add required permissions for OIDC authentication
permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Needed to checkout repository

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Debug Workspace Contents
      run: ls -R  

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build --if-present

    - name: SonarQube frontend Scan  # SonarQube scan step
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dproject.settings=sonar-project.properties
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 

    - name: Check Quality Gate  # Add this step
      uses: sonarsource/sonarqube-quality-gate-action@master
      if: always() # Always run to check even if the previous step failed
      timeout-minutes: 5
      with:
        scanTaskId: ${{ steps.sonarqube.outputs.scanTaskId }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 

    # 🔹 FIX: Configure AWS credentials using OIDC authentication
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::273354664814:role/Murali1  # Replace with your actual AWS Role ARN
        aws-region: ap-south-1

    # Upload the package to S3 bucket
    - name: Upload to S3
      run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
      
    - name: Deploying to EC2 
      run: aws deploy create-deployment --application-name webapp --deployment-group-name CodeDeployWebapp --github-location repository=${{ github.repository }},commitId=${{ github.sha }} --ignore-application-stop-failures
