name: Deploy Frontend to S3

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  

      - name: Build Frontend & Debug Output
        run: |
          npm run build  
          echo "Checking available files in the workspace..."
          ls -l
          echo "Checking inside possible build directories..."
          ls -l build/ || echo "No build directory found."
          ls -l dist/ || echo "No dist directory found."
      
      - name: Verify Build Directory
        run: |
          if [ -d "build" ]; then 
            echo "Using build directory.";
            echo "BUILD_DIR=build" >> $GITHUB_ENV;
          elif [ -d "dist" ]; then 
            echo "Using dist directory.";
            echo "BUILD_DIR=dist" >> $GITHUB_ENV;
          elif [ -d "dist/my-angular-project" ]; then 
            echo "Using Angular project dist directory.";
            echo "BUILD_DIR=dist/my-angular-project" >> $GITHUB_ENV;
          else 
            echo "Error: Build directory not found!";
            exit 1;
          fi

      - name: Compress Build Folder
        run: zip -r frontend-build.zip $BUILD_DIR/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1  

      - name: Upload ZIP to S3
        run: aws s3 cp frontend-build.zip s3://my-tf-saniakurup-bucket/

      - name: Upload Build Files to S3 (Optional)
        run: aws s3 sync $BUILD_DIR/ s3://my-tf-saniakurup-bucket/ --delete
