name: Deploy Frontend to S3

on:
  push:
    branches:
      - main  # Adjust to your deployment branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies & Build Frontend
        run: |
          npm install   # Install dependencies
          npm run build # Build frontend (React/Vue/Angular)

      - name: Compress Build Folder
        run: |
          zip -r frontend-build.zip ./build  # Adjust if using Vue/Angular (dist folder)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1  # Change to your AWS region

      - name: Upload ZIP to S3
        run: aws s3 cp frontend-build.zip s3://my-tf-saniakurup-bucket/

      - name: Invalidate CloudFront Cache (Optional)
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
